### ISSUE TITLE
Peer to peer review 

### ISSUE THREAD

**Issue by olaishola05** [tresorsawasawa/Leaderboard_App#5]
@tresorsawasawa you have done an excellent job with the project

-  The codebase is clean
- You have followed JS principle and es6 coding convention
- The App UI is amazing and sleek :sunglasses: 

But there are few improvements that are required to make the project a rockstar 
- Kindly add in the readme how to run the project locally when cloned
- Suggestion, it will be nice if you could position the add form to the top of the page before the list on the mobile screen
- Kindly provide validation for the name input to prevent the use of only a numbers

**Comment by tresorsawasawa** [comment]
Thank You :pray:
